version: "3.9"
services:
  postgres-db:
    image: postgres:16-alpine
    container_name: facile-apply-postgres-db
    restart: on-failure
    env_file:
      - database.env
    ports:
      - "5434:5432"
    volumes:
      - facile-apply_data:/var/lib/postgresql/data

volumes:
  facile-apply_data:
    external: true
    name: facile-apply_data
